import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/home.module.scss'

export default function Home() {
    return (
        <div className={styles.homeContainer}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <img src="/assets/img/logo.png" width="auto" height="100%" alt="logo-colortelecom"/>
                <div>
                    <span />
                    <span />
                    <span />
                </div>
            </header>

            <main>
                <h1>Informations du Forfait</h1>

                <div className={styles.steps}>
                    <div>
                        <p className={styles.pFill}>1</p>
                        <i class="fas fa-check"></i>
                    </div>
                    <hr className={styles.hrFill}/>
                    <div>
                        <p>2</p>
                    </div>
                    <hr className={styles.hrNotFill}/>
                    <div>
                        <p>3</p>
                    </div>
                </div>

                <div className={styles.body}>

                    <div className={styles.forfait}>
                        <div className={styles.header}>
                            <p>Mensuel</p>
                            <i class="fas fa-check"></i>
                        </div>
                        <div className={styles.bodyForfait}>
                            <div className={styles.top}>
                                <p>Forfait 10h/mois</p>
                                <span>de réception</span>
                            </div>
                            <p className={styles.infoForfait}>Sur vos fixes et mobiles</p>
                            <p className={styles.price}>14.90€ HT</p>
                        </div>
                    </div>

                    <hr />

                    <div className={styles.info}>
                        <div>
                            <p>Type de numéro :</p>
                            <span>Numéro Argent : 01 87 200 200</span>
                        </div>
                        <div>
                            <p>Zone :</p>
                            <span>Paris - 01</span>
                        </div>
                    </div>

                    <button>SUIVANT</button>

                </div>
            
            </main>

        </div>
    )
}
